FROM public.ecr.aws/lambda/python:3.12-arm64

COPY requirements.txt /tmp/requirements.txt

RUN pip install \
    --requirement /tmp/requirements.txt \
    --target /opt/python/lib/python3.12/site-packages/

RUN find /opt/python/lib/python3.12/site-packages/ -name '__pycache__' -type d -exec rm -rf {} + \
    && rm -rf /root/.cache/pip 